export const artworksData = [
  {
    "id": 1,
    "title": "火焰型土器",
    "image": "art_001.png",
    "artist": "",
    "year-plot": 570,
    "year": "縄文時代(中期)・前3000～前2000年",
    "region-plot": "鎌倉",
    "place": "伝新潟県長岡市馬高出土",
    "genre": "工芸",
    "map": "map_001.svg",
    "tags": "考古/すごい/縄文"
  },
  {
    "id": 2,
    "title": "深鉢形土器",
    "image": "art_002.png",
    "artist": "",
    "year-plot": 570,
    "year": "縄文時代(中期)・前3000～前2000年",
    "region-plot": "鎌倉",
    "place": "長野県伊那市宮ノ前出土",
    "genre": "工芸",
    "map": "map_001.svg",
    "tags": "考古/渋い/縄文"
  },
  {
    "id": 3,
    "title": "銅鐸",
    "image": "art_003.png",
    "artist": "",
    "year-plot": 580,
    "year": "弥生時代(後期)・1～3世紀",
    "region-plot": "奈良",
    "place": "和歌山県みなべ町西本庄出土",
    "genre": "工芸",
    "map": "map_001.svg",
    "tags": "考古/すごい/弥生"
  },
  {
    "id": 4,
    "title": "埴輪 盛装の男子",
    "image": "art_004.png",
    "artist": "",
    "year-plot": 600,
    "year": "古墳時代・6世紀",
    "region-plot": "鎌倉",
    "place": "栃木県壬生町 ナナシ塚古墳出土",
    "genre": "工芸",
    "map": "map_001.svg",
    "tags": "考古/かわいい/古墳"
  },
  {
    "id": 5,
    "title": "鼉龍鏡",
    "image": "art_005.png",
    "artist": "",
    "year-plot": 590,
    "year": "古墳時代・4世紀",
    "region-plot": "京都",
    "place": "山口県柳井市 柳井茶臼山古墳出土",
    "genre": "工芸",
    "map": "map_001.svg",
    "tags": "考古/かっこいい/古墳/神獣"
  },
  {
    "id": 6,
    "title": "菩薩半跏像",
    "image": "art_006.png",
    "artist": "",
    "year-plot": 700,
    "year": "飛鳥時代・7世紀",
    "region-plot": "奈良",
    "place": "和歌山県東牟婁郡那智勝浦町那智山出土",
    "genre": "彫刻",
    "map": "map_001.svg",
    "tags": "彫刻/きれい/飛鳥/仏像"
  },
  {
    "id": 7,
    "title": "紫紙金字金光明最勝王経 巻第七",
    "image": "art_007.png",
    "artist": "",
    "year-plot": 800,
    "year": "奈良時代・8世紀",
    "region-plot": "奈良",
    "place": "",
    "genre": "絵画",
    "map": "map_001.svg",
    "tags": "書跡/きれい/奈良/仏教"
  },
  {
    "id": 8,
    "title": "賢愚経断簡（大聖武）",
    "image": "art_008.png",
    "artist": "伝聖武天皇筆",
    "year-plot": 780,
    "year": "奈良時代・8世紀",
    "region-plot": "奈良",
    "place": "",
    "genre": "書跡",
    "map": "map_001.svg",
    "tags": "書跡/かっこいい/奈良/仏教"
  },
  {
    "id": 9,
    "title": "興福寺鎮壇具 瑞花双鳳八花鏡",
    "image": "art_009.png",
    "artist": "",
    "year-plot": 790,
    "year": "中国・唐時代・8世紀",
    "region-plot": "奈良",
    "place": "奈良市興福寺中金堂須弥壇下出土",
    "genre": "工芸",
    "map": "map_001.svg",
    "tags": "工芸/きれい/奈良/鏡"
  },
  {
    "id": 10,
    "title": "興福寺鎮壇具 金銅鋺",
    "image": "art_010.png",
    "artist": "",
    "year-plot": 800,
    "year": "奈良時代・8世紀",
    "region-plot": "奈良",
    "place": "奈良市興福寺中金堂須弥壇下出土",
    "genre": "工芸",
    "map": "map_001.svg",
    "tags": "工芸/きれい/奈良/仏具"
  },
  {
    "id": 11,
    "title": "寛平御時后宮歌合",
    "image": "art_011.png",
    "artist": "伝宗尊親王筆",
    "year-plot": 1050,
    "year": "平安時代・11世紀",
    "region-plot": "京都",
    "place": "",
    "genre": "書跡",
    "map": "map_002.svg",
    "tags": "書跡/きれい/平安/貴族"
  },
  {
    "id": 12,
    "title": "毘沙門天立像",
    "image": "art_012.png",
    "artist": "慶算作",
    "year-plot": 1271,
    "year": "鎌倉時代・文永8年(1271)\t",
    "region-plot": "鎌倉",
    "place": "",
    "genre": "彫刻",
    "map": "map_003.svg",
    "tags": "彫刻/かっこいい/平安/仏像"
  },
  {
    "id": 13,
    "title": "諸尊集会図",
    "image": "art_013.png",
    "artist": "",
    "year-plot": 1300,
    "year": "鎌倉時代・13世紀",
    "region-plot": "鎌倉",
    "place": "",
    "genre": "絵画",
    "map": "map_003.svg",
    "tags": "絵画/すごい/平安/密教"
  },
  {
    "id": 14,
    "title": "諸尊集会図",
    "image": "art_014.png",
    "artist": "",
    "year-plot": 1400,
    "year": "鎌倉時代・14世紀",
    "region-plot": "鎌倉",
    "place": "",
    "genre": "絵画",
    "map": "map_003.svg",
    "tags": "絵画/すごい/平安/密教"
  },
  {
    "id": 15,
    "title": "無量義経（久能寺経）",
    "image": "art_015.png",
    "artist": "",
    "year-plot": 1200,
    "year": "平安時代・12世紀",
    "region-plot": "鎌倉",
    "place": "",
    "genre": "絵画",
    "map": "map_003.svg",
    "tags": "書跡/きれい/平安/装飾経"
  },
  {
    "id": 16,
    "title": "金銅一面器",
    "image": "art_016.png",
    "artist": "",
    "year-plot": 1300,
    "year": "鎌倉時代・13世紀",
    "region-plot": "京都",
    "place": "香川・弘憲寺蔵",
    "genre": "工芸",
    "map": "map_003.svg",
    "tags": "工芸/かっこいい/鎌倉/密教"
  },
  {
    "id": 17,
    "title": "金銅金剛盤",
    "image": "art_017.png",
    "artist": "",
    "year-plot": 1250,
    "year": "鎌倉時代・13世紀",
    "region-plot": "京都",
    "place": "香川・弘憲寺蔵",
    "genre": "工芸",
    "map": "map_003.svg",
    "tags": "工芸/すごい/平安/密教"
  },
  {
    "id": 18,
    "title": "金銅五仏種子五鈷鈴",
    "image": "art_018.png",
    "artist": "",
    "year-plot": 1300,
    "year": "鎌倉時代・13世紀",
    "region-plot": "鎌倉",
    "place": "",
    "genre": "工芸",
    "map": "map_003.svg",
    "tags": "工芸/きれい/平安/密教"
  },
  {
    "id": 19,
    "title": "鶴草紙　下巻",
    "image": "art_019.png",
    "artist": "筆者不詳",
    "year-plot": 1700,
    "year": "江戸時代・17世紀",
    "region-plot": "江戸",
    "place": "",
    "genre": "絵画",
    "map": "map_003.svg",
    "tags": "絵画/かわいい/平安/物語"
  },
  {
    "id": 20,
    "title": "古今和歌集断簡（本阿弥切）",
    "image": "art_020.png",
    "artist": "伝小野道風筆",
    "year-plot": 1150,
    "year": "平安時代・11～12世紀",
    "region-plot": "京都",
    "place": "",
    "genre": "書跡",
    "map": "map_003.svg",
    "tags": "書跡/きれい/平安/貴族"
  },
  {
    "id": 21,
    "title": "拈香法語",
    "image": "art_021.png",
    "artist": "一山一寧筆",
    "year-plot": 1303,
    "year": "鎌倉時代・嘉元元年(1303)",
    "region-plot": "京都",
    "place": "京都・南禅寺蔵",
    "genre": "絵画",
    "map": "map_003.svg",
    "tags": "書跡/渋い/鎌倉/禅"
  },
  {
    "id": 22,
    "title": "四季山水図屏風",
    "image": "art_022.png",
    "artist": "伝周文筆",
    "year-plot": 1500,
    "year": "室町時代・15世紀",
    "region-plot": "京都",
    "place": "",
    "genre": "絵画",
    "map": "map_003.svg",
    "tags": "絵画/渋い/室町/水墨画"
  },
  {
    "id": 23,
    "title": "袋形水指",
    "image": "art_023.png",
    "artist": "",
    "year-plot": 1700,
    "year": "江戸時代・17世紀",
    "region-plot": "江戸",
    "place": "",
    "genre": "工芸",
    "map": "map_004.svg",
    "tags": "工芸/かわいい/江戸/茶の湯"
  },
  {
    "id": 24,
    "title": "志野茶碗 銘 振袖",
    "image": "art_024.png",
    "artist": "",
    "year-plot": 1650,
    "year": "安土桃山～江戸時代・16～17世紀",
    "region-plot": "江戸",
    "place": "",
    "genre": "工芸",
    "map": "map_004.svg",
    "tags": "工芸/渋い/桃山/茶の湯"
  },
  {
    "id": 25,
    "title": "黒楽茶碗 銘 尼寺",
    "image": "art_025.png",
    "artist": "長次郎",
    "year-plot": 1600,
    "year": "安土桃山時代・16世紀",
    "region-plot": "江戸",
    "place": "",
    "genre": "工芸",
    "map": "map_004.svg",
    "tags": "工芸/渋い/桃山/茶の湯"
  },
  {
    "id": 26,
    "title": "黒糸威二枚胴具足",
    "image": "art_026.png",
    "artist": "",
    "year-plot": 1680,
    "year": "江戸時代・17世紀",
    "region-plot": "江戸",
    "place": "",
    "genre": "工芸",
    "map": "map_005.svg",
    "tags": "工芸/かっこいい/江戸/武士"
  },
  {
    "id": 27,
    "title": "太刀",
    "image": "art_027.png",
    "artist": "",
    "year-plot": 1250,
    "year": "鎌倉時代・13世紀",
    "region-plot": "鎌倉",
    "place": "",
    "genre": "工芸",
    "map": "map_005.svg",
    "tags": "工芸/かっこいい/平安/武士"
  },
  {
    "id": 28,
    "title": "黒漆打刀",
    "image": "art_028.png",
    "artist": "",
    "year-plot": 1600,
    "year": "室町時代・16世紀",
    "region-plot": "京都",
    "place": "",
    "genre": "工芸",
    "map": "map_005.svg",
    "tags": "工芸/渋い/室町/武士"
  }
]